### ISSUE TITLE
refactor: Invalid SemVer version error needs more context

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/product-config#95]
https://github.com/stackabletech/product-config/blob/main/src/error.rs#L17-L18

This error needs to also print the actual version it is trying to parse.
Currently it just says (basically) "something is wrong" without telling us what it is trying to parse
```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/product-config/pull/96
- [ ] https://github.com/stackabletech/operator-rs/pull/682
- [ ] https://github.com/stackabletech/airflow-operator/pull/340
- [ ] https://github.com/stackabletech/druid-operator/pull/482
- [ ] https://github.com/stackabletech/hbase-operator/pull/408
- [ ] https://github.com/stackabletech/hdfs-operator/pull/416
- [ ] https://github.com/stackabletech/hive-operator/pull/384
- [ ] https://github.com/stackabletech/kafka-operator/pull/633
- [ ] https://github.com/stackabletech/nifi-operator/pull/522
- [ ] https://github.com/stackabletech/opa-operator/pull/486
- [ ] https://github.com/stackabletech/superset-operator/pull/418
- [ ] https://github.com/stackabletech/trino-operator/pull/495
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/738
```

**Comment by Techassi** [comment]
I will pick this up once I'm finished working on https://github.com/stackabletech/stackable-cockpit/pull/122.
